# Uncomment the next line to define a global platform for your project
platform :ios, '10.1'

# The target name is most likely the name of your project.
target 'LocalBall' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTPushNotification',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # RNFirebase
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core'#, '~> 5.11.0'
  pod 'Firebase/Auth'#, '~> 5.11.0'
  pod 'Firebase/Firestore'#, '~> 5.11.0'
  pod 'Firebase/Messaging'#, '~> 5.11.0'

  # Facebook login
  pod 'FBSDKCoreKit', '~> 4.38.1'
  pod 'FBSDKLoginKit', '~> 4.38.1'
  pod 'FBSDKShareKit', '~> 4.38.1'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  # Google
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'GoogleAppMeasurement'#, '~> 5.3.0'

  # RN vector icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Crashlytics
  pod 'Fabric'#, '~> 1.7.13'
  pod 'Crashlytics'#, '~> 3.10.7'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end